version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    command: uvicorn maplinker.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: maplinker.settings

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static  # Asegúrate de que esta ruta es correcta
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static:
