# Generated by Django 3.2.25 on 2024-08-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('latitud_qr1', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitud_qr1', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('latitud_qr2', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitud_qr2', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('altitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('decripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
