# Generated by Django 3.2.25 on 2024-08-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('id_nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrantes', to='nodos.nodo')),
                ('id_nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salientes', to='nodos.nodo')),
            ],
        ),
    ]
